name: build and push container

on:
  push:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

    - name: Build and push Docker image
      id: push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
        labels: ${{ steps.meta.outputs.labels }}

    - name: Build chart and release
      env:
        UPDATER_SECRET: ${{ secrets.UPDATER_SECRET }}
      run: |
        set -euxo pipefail
        export VERSION=$(date "+0.1.%Y%m%d%H%M%S")
        helm package --version "${VERSION}" --app-version "${VERSION}" charts/subsidy-ui
        helm push "subsidy-ui-${VERSION}.tgz" oci://registry.digitalocean.com/oomens-cr/helm
        
        curl "https://k8s.oomens.it/gitops-updater?name=subsidy-ui&secret=${UPDATER_SECRET}&version=${VERSION}"